.TH luufs 8
.SH NAME
.B luufs
\- mirror or merge directories
.SH SYNOPSIS
.B luufs
RO [RW] TARGET
.SH DESCRIPTION
Mirrors a directory without allowing any changes or creates a directory which
unifies the contents of two directories, while redirecting all changes to the
second one.
.SH "SEE ALSO"
.B ls(1), chroot(8), umount(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
